FileVersion = 1
Dependencies = {corlib = "*", "Atma.Common" = "*", "Atma.Entities" = "*"}

[Project]
Name = "NeonShooter"
StartupObject = "NeonShooter.Program"

[Configs.Debug.Win64]
CLibType = "Static"
