FileVersion = 1
Projects = {NeonShooter = {Path = "NeonShooter"}, SDL2 = "*", MiniZ = "*", "Atma.Common" = {Path = "../src/Atma.Common"}, HelloWorld = {Path = "HelloWorld"}}

[Workspace]
StartupProject = "NeonShooter"
