FileVersion = 1
Projects = {NeonShooter = {Path = "NeonShooter"}, "Atma.Common" = {Path = "../src/Atma.Common"}, SDL2 = "*", "Atma.OpenGL" = {Path = "../src/Atma.OpenGL"}, "Atma.SDL2" = {Path = "../src/Atma.SDL2"}, MiniZ = "*"}

[Workspace]
StartupProject = "NeonShooter"
