FileVersion = 1
Projects = {NeonShooter = {Path = "NeonShooter"}, SDL2 = "*", MiniZ = "*", "Atma.Common" = {Path = "../src/Atma.Common"}, HelloWorld = {Path = "HelloWorld"}, "Atma.Entities" = {Path = "../src/Atma.Entities"}, "Atma.Systems" = {Path = "../src/Atma.Systems"}, "Atma.Systems.Tests" = {Path = "../tests/Atma.Systems.Tests"}}

[Workspace]
StartupProject = "NeonShooter"
